- name: Install make & cmake
  become: yes
  apt:
    package:
      - make
      - cmake

- name: Install C++ Compiler
  become: yes
  apt:
    package:
      - gcc
      - g++

- name: Install git
  become: yes
  apt:
    package: git

- name: Install boost
  become: yes
  apt:
    package: libboost-all-dev

- name: Install readline
  become: yes
  apt:
    package: libreadline-dev

- name: Install libcurl
  become: yes
  apt:
    package: libcurl4-openssl-dev

- name: Install OpenJDK 11
  become: yes
  apt:
    package:
      - openjdk-11-jdk
      - maven
    state: present

- name: Download Docker apt key
  become: yes
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: 0644
    owner: root
    group: root

- name: Add Docker apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

- name: Install Docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Add user to Docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker

- name: Reset connection so that user being added to docker group takes effect
  meta: reset_connection
