- name: Install lbzip2
  become: yes
  apt:
    package: lbzip2

- name: Install wget
  become: yes
  apt:
    package: wget

- name: Download and unpack wikidata
  shell: wget -qO- https://dumps.wikimedia.org/wikidatawiki/entities/20201111/wikidata-20201111-truthy-BETA.nt.bz2 | lbzip2 -d -c > "{{ target_dir }}/datasets/wikidata-2020-11-11/wikidata-20201111-truthy-BETA.nt"
  args:
    creates: "{{ target_dir }}/datasets/wikidata-2020-11-11/wikidata-20201111-truthy-BETA.nt"
