- name: Check for the wikidata dataset
  stat:
    path: "{{ target_dir }}/datasets/wikidata-2020-11-11/wikidata-20201111-truthy-BETA.nt"
    get_checksum: no
  register: wikidata_dataset

- name: Create dataset directory
  file:
    path: "{{ target_dir }}/datasets/wikidata-2020-11-11"
    state: directory

- include: download.yaml
  when: not wikidata_dataset.stat.exists

- name: Download wikidata queries
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/tentris_compression/feasible-exmp-wikidata500-bgp-v4.txt
    checksum: sha1:d881ea12c315669ff3ef1f8073ca553e3f9b2715
    dest: "{{ target_dir }}/datasets/wikidata-2020-11-11/queries.txt"
