- name: Check for the wikidata dataset
  stat:
    path: "{{ target_dir }}/datasets/wikidata-2020-11-11"
  register: wikidata_dataset_dir

- include: download.yaml
  when: not wikidata_dataset_dir.stat.exists

- name: Download wikidata queries
  get_url:
    url: https://hobbitdata.informatik.uni-leipzig.de/tentris_compression/feasible-exmp-wikidata500-bgp-v4.txt
    checksum: sha1:d881ea12c315669ff3ef1f8073ca553e3f9b2715
    dest: "{{ target_dir }}/datasets/wikidata-2020-11-11/queries.txt"
