- name: Check for cgmemtime
  stat:
    path: /usr/local/bin/cgmemtime
  register: cgmemtime_bin

- name: Check for cgmemtime cgroup
  stat:
    path: /sys/fs/cgroup/memory/cgmemtime
  register: cgmemtime_cgroup

- include: install.yaml
  when: not cgmemtime_bin.stat.exists
